### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Nooberieno** [mukulve/Code-Editor#2]
Hi,

I noticed some issues with the way you are licensing your Code-Editor project, that you may want to change.

1. License missing year and name.
2. License being located in the README.md file

I would recommend adding the year of when the project started. (2024 looking through the commit history) and adding your name or github username after.

Also consider adding the license in a seperate LICENSE or LICENSE.md file to keep the README more readable. If the license is located in the a LICENSE or LICENSE.md file it will still be clearly visible in githubs web interface, so people will still see that the project is licensed

**Comment by mukulve** [comment]
Thanks for your feedback!

I have moved the license to a LICENSE.md file and have added a year and name.
